[deps]
ITensorBase = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"

[sources.ITensorBase]
path = ".."

[compat]
ITensorBase = "0.7"
MatrixAlgebraKit = "0.2, 0.3, 0.4, 0.5, 0.6"
